[tool.poetry]
name = "script.elementum.jackett"
version = "0.0.1"
description = ""
authors = ["Fugkco <fugkco@github.io>"]
license = "WTFPL"

[tool.poetry.dependencies]
python = "^2.7"
requests = "^2.23.0"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]
kodistubs = "^18.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
